# Makefile.utils - Reusable Utility Functions
#
# Provides: areyousure function and target
#
# Usage in other Makefiles:
#   dangerous_target: areyousure
#       @echo "doing something dangerous"

define areyousure
	@if [ "$$INFRA_NO_CONFIRM" = "1" ]; then \
		echo "INFRA_NO_CONFIRM=1, skipping confirmation"; \
	else \
		echo -n "Are you sure? [y/N] " && read ans && [ $${ans:-N} = y ]; \
	fi
endef

areyousure:
	$(call areyousure)
.PHONY: areyousure
